server:
  port: 8085

spring:
  application:
    name: Config-Service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/rp6952776/Microservice-Config
          clone-on-start: true