server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HotelService
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update