server:
  port: 8086

spring:
  application:
    name: Api-Gateway


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-25714271.okta.com/oauth2/default
    audience: api://default
    client-id: 0oam4nv7gewnTjCyH5d7
    client-secret: ddstSHm8jNYmPB4N06LtipAIXEfgmPkT2Yv_QrHpYkiEH4CqewgsGLPZZ8yVVhKS
    scopes: openid, profile, email, offline_access