server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserService
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:8085



